### ISSUE TITLE
puppeteer dependency

### ISSUE THREAD

**Issue by oytuntez** [marcolink/redash-tools#4]
Hey Marco,

Thank you for the great library. I discovered it as I was just starting to write a similar one for my need – I am glad I googled it beforehand. :)

There is a puppeteer dependency on your JS client, that is causing issues with browser usage. Do you mind removing it or putting it under devDependencies?

Oytun

**Comment by marcolink** [comment]
Hi @oytuntez 

Great to hear you like it!

My plan is to remove the snapshot functionality into its own plugin, to make the client also work in browser environments.
 
Puppeteer is needed to create snapshots, and can't be just moved to devDependencies.
https://github.com/marcolink/redash-tools/blob/master/packages/client/src/query-snapshot.ts

(The lib was mainly developed for node envs, but I get the point - would be cool to enable it also for browsers envs)

**Comment by marcolink** [comment]
Hi @oytuntez 

I extracted the snapshot functionality into it's dedicated package including the puppeteer dependency. 
The client should now also work in browser environments. 

https://github.com/marcolink/redash-tools/pull/7

**Comment by marcolink** [comment]
... and released :)
